### ISSUE TITLE
Animate opacity?

### ISSUE THREAD

**Issue by 1075dn** [rorystephenson/flutter_map_marker_popup#18]
Hi,

Great plugin! Is there a way to fade the popups in and out?

Thanks so much!

**Comment by rorystephenson** [comment]
Thanks @1075dn !

Hmm so fading in should be easily possible, here's a quick example with a custom Popup:

```dart
class FadingExamplePopup extends StatefulWidget {
  FadingExamplePopup({Key key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => _FadingExamplePopupState();
}

class _FadingExamplePopupState extends State<FadingExamplePopup> {
  bool _visible = false;
  Timer _timer;

  _FadingExamplePopupState();

  @override
  void initState() {
    super.initState();

    _timer = Timer(
      Duration(milliseconds: 100),
      () {
        setState(() {
          _visible = true;
        });
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedOpacity(
      // If the widget is visible, animate to 0.0 (invisible).
      // If the widget is hidden, animate to 1.0 (fully visible).
      opacity: _visible ? 1.0 : 0.0,
      duration: Duration(milliseconds: 200),
      // The green box must be a child of the AnimatedOpacity widget.
      child: Container(
        width: 200.0,
        height: 100.0,
        color: Colors.green,
      ),
    );
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }
}
```

Fading out is a little bit trickier because there is not a straightforward place to trigger the fade (it can't be done in onDispose).

Animations when the Widget is getting disposed probably requires a change to this plugin 🤔 .

**Comment by 1075dn** [comment]
@rorystephenson Thanks so much! Fading out was actually the part I was having trouble with. What kind of change do you mean? Maybe I can try to help...

**Comment by rorystephenson** [comment]
Hi @1075dn ! 

So I started looking at some options for how to add this and in general animating the removal of a widget is kind of tricky as you have to first run the removal animation and, after the animation has finished, actually remove the widget from the widget tree. I didn't want to make the user wait for the popup removal animation before opening a new popup (even if it should be quick) which means this plugin also needs to be able to handle multiple popups showing at once which it doesn't currently support.

Since popups can be overlapping they need to be contained in a Stack and whilst fading-in can easily be done in a stack... fading out is generally tricky as previously mentioned.

It seemed like an interesting problem so I took some (a lot of) inspiration from Flutter's AnimatedList and created an AnimatedStack widget which takes care of the adding/removing/triggering animations. That's now released in a [new package](https://pub.dev/packages/animated_stack_widget). Next I need to work on integrating that in to this plugin which will probably take some time.

Just wanted to let you know I haven't forgotten and some progress has been made!

**Comment by 1075dn** [comment]
Amazing, thanks! Keep it up, and keep us posted!

**Comment by 1075dn** [comment]
@rorystephenson You are awesome! Thanks so much!

My popups have `BackdropFilter` widgets in them, but the blur filter only seems to work when the popup is not animating. Do you happen to know why? (Is this an issue for `AnimatedStack`?)
![recorded issue](https://user-images.githubusercontent.com/66363175/118639093-308c7200-b7e0-11eb-9a24-7c6c6fb83d5d.gif)

**Comment by rorystephenson** [comment]
You noticed before I remembered to mention it here :).

Hmm so it may require you to change the blur mode, here are some related issues/PRs/comments I found:

 * https://github.com/flutter/flutter/issues/43750
 * https://github.com/flutter/flutter/issues/31706#issuecomment-522697161
 * https://github.com/flutter/flutter/pull/80129
 * https://github.com/flutter/flutter/issues/81322

**Comment by 1075dn** [comment]
Thanks for looking into it! I guess we'll have to wait until the `BackdropFilter`'s `blendMode` property is released in the stable channel...

**Comment by rorystephenson** [comment]
I didn't realise it wasn't released yet but I'm glad a solution is on its way! I will close this for now as it seems like no changes will be needed in this package but if that's not the case feel free to re-open.
