### ISSUE TITLE
Problem when rotating the map

### ISSUE THREAD

**Issue by hpassos2b** [rorystephenson/flutter_map_marker_popup#19]
![image](https://user-images.githubusercontent.com/83711686/118543636-e7c6b180-b72a-11eb-8139-f1a0c8fa44c0.png)

The PopUp rotates too, is there anything I can do? Or is it an issue? Thank you.

**Comment by rorystephenson** [comment]
Hi @hpassos2b !

I've noticed this recently (I don't allow rotation in my app so it took me a while to notice). It needs some work in order to be supported properly. There is a WIP pull request but it's not quite working yet.

I was considering tackling it once flutter_map goes null safe and makes a new release since they have reworked the marker displaying code and I want to copy and adapt it in this plugin.

**Comment by hpassos2b** [comment]
Not allow rotation is a good work around for while, thank you.

**Comment by rorystephenson** [comment]
Please try out the new version (1.0.0)!

If you want to see how the options work and what is possible try out the updated example.
