### ISSUE TITLE
How to show the popup by default?

### ISSUE THREAD

**Issue by woshitom** [rorystephenson/flutter_map_marker_popup#30]
How can I display the popup by default when the popup is buit?

**Comment by rorystephenson** [comment]
> How can I display the popup by default when the popup is built?

Hi @woshitom . Can you elaborate on what you mean by  "by default"? Would this mean that the popup is showing always for all markers?

**Comment by woshitom** [comment]
Hi @rorystephenson yes indeed I'd like to show the popup for all markers.
Right now I'm using:

`_mapController.onReady?.then((value) {
      _popupLayerController.togglePopup(currentMakers[0]);
      _popupLayerController.togglePopup(currentMakers[1]);
  });`

But only one popup is being displayed.

**Comment by rorystephenson** [comment]
@woshitom Ah OK, right now all other popups are automatically hidden when showing a popup. The internal design wouldn't need massive changes to allow multiple popups to show at the same time. I will try to get to that soon but feel free to open a PR as well if you want to give it a try.

**Comment by rorystephenson** [comment]
@woshitom I've just published a new version (`2.0.0`) which now supports showing multiple popups at the same time.

You should be able to set the `PopupController`'s `initiallySelectedMarkers` to your list of markers to make them all show.

You will also probably want to check out the new `MarkerTapBehavior` option which allows you to control what happens when a marker is tapped. If you want nothing to happen when tapping a Marker then use `MarkerTapBehavior.none()`, if you want to toggle the tapped marker's popup use `MarkerTapBehavior.togglePopup()` or if you want to do something different you can perform a custom action with `MarkerTapBehavior.custom((marker, popupController) { /* do custom thing */})`.

I'm going to close this issue as I think it is resolved now but if you have any issues just comment here and I will re-open and have a look :).

**Comment by woshitom** [comment]
hi @rorystephenson thank you so much! cheers

**Comment by r-shahpasand** [comment]
I can't find the `initiallySelectedMarkers`. What is the best approach to keep popups open permanently (I don't want user can close a popup)?

**Comment by rorystephenson** [comment]
> I can't find the `initiallySelectedMarkers`. What is the best approach to keep popups open permanently (I don't want user to close a popup)?

https://github.com/rorystephenson/flutter_map_marker_popup/blob/bd5bbee33a85f479d1f3494cda9b324d57feb524/lib/src/options/popup_marker_layer_options.dart#L77
