### ISSUE TITLE
Can we use popups with Polygons?

### ISSUE THREAD

**Issue by aytunch** [rorystephenson/flutter_map_marker_popup#38]
@rorystephenson Hi:)
I know when and which PolyGon a user presses by the below code
Is there a way to show popup around the tapped polygon with this plugin?

```
body: FlutterMap(
        mapController: mapController,
        options: MapOptions(
          // controller: mapController,
          interactiveFlags: InteractiveFlag.all & ~InteractiveFlag.rotate,
          center: LatLng(40.980222, 29.036929),
          onTap: (tapPosition, latlng) {
            onPolygon(latlng);
          },
        ),
```

**Comment by rorystephenson** [comment]
Hi @aytunch .

While that's not the goal of this package you can probably achieve the affect as follows:

Have a Marker for each each polygon in the PopupMarkerLayerWidget. The marker can have zero width/height (to avoid it capturing touch events) and should have the latitude/longitude of where you want the popup to appear for the polygon (or have the popup snap to the map instead of the polygon). Then when the user taps a polygon, call `showPopupsOnlyFor` on your `PopupController` using that polygon's Marker.
