### ISSUE TITLE
Can't use along flutter_map ^2.0.0

### ISSUE THREAD

**Issue by Harishwarrior** [rorystephenson/flutter_map_marker_popup#47]
If i try to use this plugin along with flutter map ^2.0.0. It throws the error.

```
Because flutter_map_marker_popup >=2.2.0 depends on flutter_map ^1.0.0 and flutter_map_arcgis 2.0.0 depends on flutter_map ^0.14.0, flutter_map_marker_popup >=2.2.0 is incompatible with flutter_map_arcgis 2.0.0.
And because no versions of flutter_map_arcgis match >2.0.0 <3.0.0, flutter_map_marker_popup >=2.2.0 is incompatible with flutter_map_arcgis ^2.0.0.
So, because servicerequest depends on both flutter_map_arcgis ^2.0.0 and flutter_map_marker_popup ^3.1.0+1, version solving failed.
pub get failed (1; So, because servicerequest depends on both flutter_map_arcgis ^2.0.0 and flutter_map_marker_popup ^3.1.0+1, version solving failed.)
```

Can you update the dependency flutter_map to the latest version ?.

**Comment by hendrikdewilde** [comment]
Same Error for me too.

pub get

Running "flutter pub get" in .....
Because flutter_map_marker_popup 3.1.0+1 depends on flutter_map ^1.0.0 and no versions of flutter_map_marker_popup match >3.1.0+1 <4.0.0, flutter_map_marker_popup ^3.1.0+1 requires flutter_map ^1.0.0.
So, because ..... depends on both flutter_map ^2.0.0 and flutter_map_marker_popup ^3.1.0+1, version solving failed.
pub get failed (1; So, because ..... depends on both flutter_map ^2.0.0 and flutter_map_marker_popup ^3.1.0+1, version solving failed.)
Process finished with exit code 1

Flutter Doctor:
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.795], locale en-ZA)
• Flutter version 3.0.2 at C:\src\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision cd41fdd495 (5 weeks ago), 2022-06-08 09:52:13 -0700
• Engine revision f15f824b57
• Dart version 2.17.3
• DevTools version 2.12.2
• No issues found!

**Comment by Harishwarrior** [comment]
> Same Error for me too.
> 
> pub get
> 
> Running "flutter pub get" in .....
> Because flutter_map_marker_popup 3.1.0+1 depends on flutter_map ^1.0.0 and no versions of flutter_map_marker_popup match >3.1.0+1 <4.0.0, flutter_map_marker_popup ^3.1.0+1 requires flutter_map ^1.0.0.
> So, because ..... depends on both flutter_map ^2.0.0 and flutter_map_marker_popup ^3.1.0+1, version solving failed.
> pub get failed (1; So, because ..... depends on both flutter_map ^2.0.0 and flutter_map_marker_popup ^3.1.0+1, version solving failed.)
> Process finished with exit code 1
> 
> Flutter Doctor:
> [√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.795], locale en-ZA)
> • Flutter version 3.0.2 at C:\src\flutter
> • Upstream repository https://github.com/flutter/flutter.git
> • Framework revision cd41fdd495 (5 weeks ago), 2022-06-08 09:52:13 -0700
> • Engine revision f15f824b57
> • Dart version 2.17.3
> • DevTools version 2.12.2
> • No issues found!

You can try this Fork for now #48

**Comment by hendrikdewilde** [comment]
Thank you

**Comment by aytunch** [comment]
@Harishwarrior thanks for the fork. It was useful.
Can we merge this PR?
Because of this, we can't upgrade the clustering package as well
https://github.com/lpongetti/flutter_map_marker_cluster/issues/124

**Comment by rorystephenson** [comment]
Sorry for the delay! 3.2.0 is published now with flutter_map v2 support.

**Comment by rdehuyss** [comment]
Thanks, @rorystephenson !!
