### ISSUE TITLE
"Floating" Popup Widget

### ISSUE THREAD

**Issue by olliegardner** [rorystephenson/flutter_map_marker_popup#8]
First of all, thanks for developing this plugin - it's great.

I'm just wondering if it is possible to have the popup widget "float" above the map instead of being embedded into the map layer? The behaviour would be the same as a typical floating action button.

**Comment by rorystephenson** [comment]
Hi @olliegardner .

>First of all, thanks for developing this plugin - it's great.
Thanks a lot!

>I'm just wondering if it is possible to have the popup widget "float" above the map instead of being embedded into the map layer? The behaviour would be the same as a typical floating action button.

It depends exactly how you want it to work. If you just want say a popup with a fixed position relative to the map widget (bottom center of the map for example) then this functionality could be added to this plugin, probably without too much work.

If you're looking for something that behaves more like an `Overlay` widget (can be outside the bounds of the map and may still be shown after the map is destroyed) that would probably belong in a separate plugin/implementation since it would require managing the popup in quite a different way.

Maybe you can provide some more details on what you're hoping to achieve?

**Comment by olliegardner** [comment]
Your 1st suggestion is exactly what I'm looking for! A popup which could appear at the bottom of the screen which has a fixed position would be great please

**Comment by rorystephenson** [comment]
@olliegardner I don't have time to work on this yet (although I would really like to!). If you want to try yourself I can give you some suggestions, otherwise I hope to get to this eventually.

**Comment by Swepilot** [comment]
@olliegardner did you find/create a solution for this? I'm looking for that same...

**Comment by rorystephenson** [comment]
Hi @olliegardner and @Swepilot . I've just added this option. You can now choose to snap the popup position to the map itself rather than just the marker.

See the new PopupSnap options here: https://github.com/rorystephenson/flutter_map_marker_popup/blob/c17c8d5a0b7a2ea7efd892514632ff1b7b5b5626/lib/src/popup_snap.dart#L17-L21

So for example to have the dialog show at the bottom of the map you can use `PopupSnap.mapBottom`.

**Comment by Swepilot** [comment]
That's an amazing improvement. I will get on to testing that very shortly 👍

**Comment by rorystephenson** [comment]
@Swepilot and @olliegardner I'm going to close this now on the assumption that it's working. Please open a new issue if there are any problems!

**Comment by pablojimpas** [comment]
> @Swepilot and @olliegardner I'm going to close this now on the assumption that it's working. Please open a new issue if there are any problems!

afaik using PopupSnap.mapBottom places the popup below a tipical FloatingActionButton for example, will it be possible to display it above the FAB in an easy way?

**Comment by rorystephenson** [comment]
Hi @pablojimpas . Right now it would not be possible to show it above the FAB. For that to work you would need to use an Overlay widget rather than just adding the widget to the map as this package does. Overlays are more complicated and have to be managed carefully to avoid them staying visible when they no longer should be (e.g. when changing page). I'm not 100% against it but my gut feeling is that it doesn't belong in this package.

**Comment by pablojimpas** [comment]
Okey @rorystephenson, no worries. I'll prefer to step away from the complexity and performance implications of using Overlays. Maybe a quick solution it's to just hide the FAB when a bottom popup appears using whatever state management solution the app developer wants.

**Comment by rorystephenson** [comment]
> Okey @rorystephenson, no worries. I'll prefer to step away from the complexity and performance implications of using Overlays. Maybe a quick solution it's to just hide the FAB when a bottom popup appears using whatever state management solution the app developer wants.

Sounds like it could work. Another potential idea for you: implement a FAB map layer and put it below the popup layer.

**Comment by rorystephenson** [comment]
@pablojimpas FYI with the release of v3.0.0 you can now show the popups where/how you like! Check out the 'Popup outside of map' example :).

**Comment by pablojimpas** [comment]
> @pablojimpas FYI with the release of v3.0.0 you can now show the popups where/how you like! Check out the 'Popup outside of map' example :).

Thanks @rorystephenson!! I'll take a look at your latest commits for that release and reconsider the way I achieve this behavior in my apps.
